"use client";

import { driver } from "driver.js";
import "driver.js/dist/driver.css";
import { useCallback } from "react";

export const useTour = () => {
  const startCoachTour = useCallback(() => {
    const driverObj = driver({
      showProgress: true,
      animate: true,
      smoothScroll: true,
      stagePadding: 12,
      overlayColor: "rgba(10, 10, 15, 0.9)",
      popoverClass: "nutrisnap-driver-popover",
      steps: [
        {
          element: "#coach-stats",
          popover: {
            title: "Performance Metrics",
            description: "Track your coaching impact, active clients, and program success rates at a glance.",
            side: "bottom",
            align: "start",
          },
        },
        {
          element: "#client-overview",
          popover: {
            title: "Client Management",
            description: "Monitor each athlete's adherence, current program, and compliance in real-time.",
            side: "top",
            align: "start",
          },
        },
        {
          element: "#invite-client-btn",
          popover: {
            title: "Grow Your Team",
            description: "Ready to take on more athletes? Use this to send personalized invites to new clients.",
            side: "left",
            align: "center",
          },
        },
        {
          element: "#activity-feed",
          popover: {
            title: "Live Activity Log",
            description: "Stay updated with every meal logged and workout completed by your athletes.",
            side: "left",
            align: "start",
          },
        },
        {
          element: "#pending-requests",
          popover: {
            title: "New Opportunities",
            description: "Review and accept incoming coaching requests from interested athletes.",
            side: "top",
            align: "start",
          },
        },
      ],
    });

    driverObj.drive();
  }, []);

  const startMemberTour = useCallback(() => {
    const driverObj = driver({
      showProgress: true,
      animate: true,
      smoothScroll: true,
      stagePadding: 12,
      overlayColor: "rgba(10, 10, 15, 0.9)",
      popoverClass: "nutrisnap-driver-popover",
      steps: [
        {
          element: "#member-stats",
          popover: {
            title: "Daily Nutrition Snapshot",
            description: "Instantly see how many calories and protein you've consumed vs. your goals.",
            side: "bottom",
            align: "start",
          },
        },
        {
          element: "#water-card",
          popover: {
            title: "Hydration Tracking",
            description: "Keep your performance sharp by tracking your water intake throughout the day.",
            side: "right",
            align: "start",
          },
        },
        {
          element: "#ai-focus-card",
          popover: {
            title: "AI Daily Focus",
            description: "Our AI analyzes your data to give you personalized recommendations for fiber, recovery, and more.",
            side: "left",
            align: "start",
          },
        },
        {
          element: "#active-workout",
          popover: {
            title: "Training Headquarters",
            description: "Access your custom protocols designed by your coach or generated by AI.",
            side: "top",
            align: "start",
          },
        },
        {
          element: "#weekly-summary",
          popover: {
            title: "Weekly Performance",
            description: "Review your consistency and AI-driven insights from the past 7 days.",
            side: "top",
            align: "start",
          },
        },
        {
          element: "#nutrition-charts",
          popover: {
            title: "Visual Progress",
            description: "Deep dive into your calorie and protein trends with high-fidelity charts.",
            side: "top",
            align: "start",
          },
        },
        {
          element: "#meals-card",
          popover: {
            title: "Meal Log",
            description: "Review everything you've eaten today and add new logs easily.",
            side: "top",
            align: "start",
          },
        },
      ],
    });

    driverObj.drive();
  }, []);

  return { startCoachTour, startMemberTour };
};
